version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                CLUSTER_URL: ${CLUSTER_URL}
                WS_URL: ${WS_URL}
        ports:
            - "3000:3000"
        env_file:
            - .env
        environment:
            - PORT=3000
            - CLUSTER_URL=${CLUSTER_URL}
            - WS_URL=${WS_URL}
        command: ["node", "dist/main.js"]
